$schema: 'https://schema.postman.com/environment/v1'
name: Scholarship Local
values:
  - key: baseUrl
    value: 'http://localhost:3000'
    enabled: true
  - key: studentToken
    value: ''
    enabled: true
  - key: employeeToken
    value: ''
    enabled: true
  - key: adminToken
    value: ''
    enabled: true
  - key: categoryId
    value: ''
    enabled: true
  - key: countryId
    value: ''
    enabled: true
  - key: universityId
    value: ''
    enabled: true
  - key: scholarshipId
    value: ''
    enabled: true
