import { DatePipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ApplicationStatus, ScholarshipApplication } from '../../../core/models/application.models';
import { ApplicationService } from '../../../core/services/application.service';
import { apiErrorMessage } from '../../../core/services/error-message';
import { ApplicationJourneyComponent } from '../../../shared/components/application-journey/application-journey.component';
import { StatusBadgeComponent } from '../../../shared/components/status-badge/status-badge.component';
import { UiStateComponent } from '../../../shared/components/ui-state/ui-state.component';
import { environment } from '../../../../environments/environment';

@Component({selector:'app-employee-applications',standalone:true,imports:[DatePipe,ReactiveFormsModule,ApplicationJourneyComponent,StatusBadgeComponent,UiStateComponent],template:`<section class="management-page"><header class="page-header"><p class="eyebrow">APPLICATION REVIEW</p><h1>Review by application ID</h1><p>The current backend supports employee lookup and status updates by ID, but not an assigned-applications list.</p></header><form class="lookup-bar" [formGroup]="lookupForm" (ngSubmit)="lookup()"><input formControlName="id" placeholder="24-character MongoDB application ID"><button class="button primary" type="submit" [disabled]="lookupForm.invalid || loading()">{{loading()?'Looking up…':'Find application →'}}</button></form>@if(error()){<div class="alert error">{{error()}}</div>}@if(application();as item){<div class="review-grid"><div><app-application-journey [application]="item"/><section class="management-card"><div class="section-heading"><p class="eyebrow">APPLICATION CONTENT</p><h2>Submitted information</h2></div><dl class="record-details"><div><dt>Student ID</dt><dd>{{item.studentId}}</dd></div><div><dt>Application ID</dt><dd>{{item._id}}</dd></div><div><dt>Created</dt><dd>{{item.createdAt|date:'medium'}}</dd></div><div><dt>Submitted</dt><dd>{{(item.submittedAt|date:'medium')||'Not submitted'}}</dd></div></dl><h3>Answers</h3>@for(answer of item.answers;track answer.question){<div class="answer-block"><b>{{answer.question}}</b><p>{{answer.answer}}</p></div>}@empty{<p class="muted">No custom answers supplied.</p>}<h3>Documents attached to application</h3>@for(document of item.documents;track document.fileUrl){<a class="document-link" [href]="fileUrl(document.fileUrl)" target="_blank">{{document.name}} ↗</a>}@empty{<p class="muted">No documents attached to this application.</p>}</section></div><aside class="management-card review-actions"><p class="eyebrow">DECISION DESK</p><h2>Move journey forward</h2><app-status-badge [status]="item.status"/><label>Review note<textarea rows="5" [formControl]="note" placeholder="Explain the next step to the student"></textarea></label><div class="decision-buttons">@for(next of transitions(item.status);track next){<button class="button" [class.primary]="next==='under_review'||next==='accepted'" [class.danger]="next==='rejected'" type="button" (click)="update(next)">{{next.replaceAll('_',' ')}}</button>}@empty{<p class="muted">No further status transitions are allowed.</p>}</div></aside></div>}@else if(!loading()&&!error()){<app-ui-state title="Enter an application ID" message="Open one application securely using the existing GET /applications/:id route."/>}</section>`})
export class EmployeeApplicationsComponent{private readonly fb=inject(FormBuilder);private readonly api=inject(ApplicationService);readonly application=signal<ScholarshipApplication|null>(null);readonly loading=signal(false);readonly error=signal('');readonly lookupForm=this.fb.nonNullable.group({id:['',[Validators.required,Validators.pattern(/^[a-f\d]{24}$/i)]]});readonly note=this.fb.nonNullable.control('');lookup(){if(this.lookupForm.invalid)return;this.loading.set(true);this.error.set('');this.application.set(null);this.api.getById(this.lookupForm.controls.id.value).subscribe({next:({data})=>{this.application.set(data);this.loading.set(false);},error:(error:unknown)=>{this.error.set(apiErrorMessage(error,'Application not found.'));this.loading.set(false);}});}fileUrl(fileUrl:string):string{return fileUrl.startsWith('http')?fileUrl:`${environment.uploadsUrl}${fileUrl}`;}transitions(status:ApplicationStatus):ApplicationStatus[]{const map:Partial<Record<ApplicationStatus,ApplicationStatus[]>>={submitted:['under_review'],under_review:['accepted','rejected','missing_documents'],missing_documents:['under_review','rejected']};return map[status]??[];}update(status:ApplicationStatus){const current=this.application();if(!current)return;this.api.updateStatus(current._id,status,this.note.value).subscribe({next:({data})=>{this.application.set(data);this.note.setValue('');},error:(error:unknown)=>this.error.set(apiErrorMessage(error))});}}
