import { Component, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Scholarship } from '../../../core/models/scholarship.models';
import { ScholarshipService } from '../../../core/services/scholarship.service';
import { StatCardComponent } from '../../../shared/components/stat-card/stat-card.component';
import { UiStateComponent } from '../../../shared/components/ui-state/ui-state.component';

@Component({ selector:'app-employee-dashboard',standalone:true,imports:[RouterLink,StatCardComponent,UiStateComponent],template:`<section class="management-page"><header class="page-header split"><div><p class="eyebrow">EMPLOYEE DESK</p><h1>Review workspace</h1><p>Manage the scholarship catalog and review an application when you have its ID.</p></div><a routerLink="/employee/applications" class="button primary">Review by ID →</a></header><div class="management-stats"><app-stat-card label="Catalog records" [value]="scholarships().length" caption="Loaded from API" icon="✦"/><app-stat-card label="Assigned applications" value="—" caption="Listing API not exposed" icon="◎"/><app-stat-card label="Under review" value="—" caption="Listing API not exposed" icon="◷"/><app-stat-card label="Completed reviews" value="—" caption="Listing API not exposed" icon="✓"/></div><section class="management-card api-gap-card"><div><p class="eyebrow">BACKEND CAPABILITY NOTE</p><h2>Assigned queue is not exposed yet</h2><p>The service contains assignment logic, but the current routes do not expose an employee list or assignment endpoint. This frontend therefore offers secure lookup by application ID and does not invent a route.</p></div><a routerLink="/employee/applications" class="button ghost">Open review lookup</a></section><section class="management-card"><div class="section-heading split"><div><p class="eyebrow">RECENT CATALOG</p><h2>Scholarships</h2></div><a routerLink="/employee/scholarships" class="text-link">Manage catalog →</a></div><div class="mini-records">@for(item of scholarships().slice(0,5);track item._id){<article><span>{{item.status}}</span><div><b>{{item.title}}</b><small>{{item.provider}}</small></div><time>{{item.deadline.slice(0,10)}}</time></article>}@empty{<app-ui-state [compact]="true" title="No catalog records" message="Create scholarships from the catalog page."/>}</div></section></section>`})
export class EmployeeDashboardComponent{private readonly api=inject(ScholarshipService);readonly scholarships=signal<Scholarship[]>([]);constructor(){this.api.list({limit:100}).subscribe({next:({data})=>this.scholarships.set(data),error:()=>undefined});}}
