import { DecimalPipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { forkJoin, finalize } from 'rxjs';
import { StudentDocument } from '../../../core/models/notification.models';
import { StudentProfile } from '../../../core/models/user.models';
import { AuthService } from '../../../core/services/auth.service';
import { DocumentService } from '../../../core/services/document.service';
import { apiErrorMessage } from '../../../core/services/error-message';
import { StudentService } from '../../../core/services/student.service';
import { UserService } from '../../../core/services/user.service';
import { StatusBadgeComponent } from '../../../shared/components/status-badge/status-badge.component';
import { ProgressRingComponent } from '../../../shared/components/progress-ring/progress-ring.component';
import { I18nService } from '../../../core/i18n/i18n.service';
import { passwordMatchValidator } from '../../../core/validators/password-match.validator';

@Component({
  selector: 'app-profile', standalone: true, imports: [DecimalPipe, ReactiveFormsModule, ProgressRingComponent, StatusBadgeComponent],
  template: `
    <section class="page-hero compact page-container"><p class="eyebrow">TRAVELER PROFILE</p><h1>Build your Opportunity <span>Passport.</span></h1><p>These are the exact profile fields supported by the student profile API.</p></section>
    <section class="profile-layout page-container">
      <aside class="profile-card"><div class="profile-avatar">{{ initials() }}</div><h2>{{ auth.currentUser()?.name }}</h2><p>{{ auth.currentUser()?.email }}</p><app-progress-ring [value]="completion()" [small]="true" /><p class="muted">Complete academic and personal details to strengthen your passport.</p></aside>
      <div class="profile-content">
        @if (error()) { <div class="alert error">{{ error() }}</div> } @if (success()) { <div class="alert success">{{ success() }}</div> }
        <section class="content-card"><div class="section-heading"><p class="eyebrow">ACCOUNT</p><h2>Passport holder</h2></div><form [formGroup]="accountForm" (ngSubmit)="saveAccount()"><div class="form-row"><label>Full name<input formControlName="name" autocomplete="name"></label><label>Email<input type="email" formControlName="email" autocomplete="email"></label></div><button class="button primary" type="submit" [disabled]="accountForm.invalid || saving()">Save account</button></form></section>
        <section class="content-card"><div class="section-heading"><p class="eyebrow">SECURITY</p><h2>Change password</h2></div><form [formGroup]="passwordForm" (ngSubmit)="changePassword()"><label>Current password<input type="password" formControlName="currentPassword" autocomplete="current-password"></label><div class="form-row"><label>New password<input type="password" formControlName="newPassword" autocomplete="new-password" placeholder="Minimum 6 characters"></label><label>Confirm new password<input type="password" formControlName="confirmPassword" autocomplete="new-password"></label></div>@if (passwordForm.hasError('passwordMismatch') && passwordForm.controls.confirmPassword.touched) { <small class="validation-message">New passwords do not match.</small> }<button class="button primary" type="submit" [disabled]="passwordForm.invalid || changingPassword()">{{ changingPassword() ? 'Updating password…' : 'Change password' }}</button></form></section>
        <form [formGroup]="profileForm" (ngSubmit)="saveProfile()">
          <section class="content-card"><div class="section-heading"><p class="eyebrow">PERSONAL INFORMATION</p><h2>Your coordinates</h2></div><div class="form-row"><label>Phone<input formControlName="phone"></label><label>Date of birth<input type="date" formControlName="dateOfBirth"></label></div><div class="form-row"><label>Gender<select formControlName="gender"><option value="">Select</option><option value="Male">Male</option><option value="Female">Female</option></select></label><label>Nationality<input formControlName="nationality"></label></div><div class="form-row"><label>Country<input formControlName="country"></label><label>Address<input formControlName="address"></label></div></section>
          <section class="content-card"><div class="section-heading"><p class="eyebrow">ACADEMIC RECORD</p><h2>Your current position</h2></div><div class="form-row"><label>University<input formControlName="university"></label><label>Faculty<input formControlName="faculty"></label></div><div class="form-row"><label>Department<input formControlName="department"></label><label>Degree<select formControlName="degree"><option value="">Select</option><option>Bachelor</option><option>Master</option><option>PhD</option></select></label></div><div class="form-row"><label>Graduation year<input type="number" formControlName="graduationYear"></label><label>GPA (0–4)<input type="number" step="0.01" formControlName="GPA"></label></div></section>
          <section class="content-card"><div class="section-heading"><p class="eyebrow">DESTINATION PREFERENCES</p><h2>Where you want to go</h2></div><div class="form-row"><label>Target degree<select formControlName="targetDegreeLevel"><option value="">Select</option><option>Bachelor</option><option>Master</option><option>PhD</option></select></label><label>English level<select formControlName="englishLevel"><option value="">Select</option>@for (level of ['A1','A2','B1','B2','C1','C2']; track level) { <option>{{ level }}</option> }</select></label></div><div class="form-row"><label>IELTS<input type="number" step="0.5" formControlName="IELTS"></label><label>TOEFL<input type="number" formControlName="TOEFL"></label></div><label>Preferred majors <small>comma separated</small><input formControlName="preferredMajors"></label><label>Preferred countries <small>comma separated</small><input formControlName="preferredCountries"></label><label>Skills <small>comma separated</small><input formControlName="skills"></label><label>Languages <small>comma separated</small><input formControlName="languages"></label><label>Interests <small>comma separated</small><input formControlName="interests"></label><label>Bio<textarea rows="5" formControlName="bio" maxlength="1000"></textarea></label><button class="button primary" type="submit" [disabled]="profileForm.invalid || saving()">{{ saving() ? 'Saving passport…' : 'Save profile →' }}</button></section>
        </form>
        <section class="content-card"><div class="section-heading split"><div><p class="eyebrow">DOCUMENT WALLET</p><h2>Travel-ready files</h2></div><span class="muted">PDF/JPG/PNG · max set by backend</span></div><form class="upload-row" [formGroup]="uploadForm" (ngSubmit)="upload()"><select formControlName="type"><option value="">Document type</option>@for (type of documentTypes; track type) { <option>{{ type }}</option> }</select><input type="file" (change)="pickFile($event)" accept=".pdf,.jpg,.jpeg,.png"><button class="button primary" type="submit" [disabled]="!selectedFile || uploadForm.invalid || uploading()">{{ uploading() ? 'Uploading…' : 'Upload' }}</button></form><div class="document-list">@for (document of documents(); track document._id) { <article><span class="file-icon">DOC</span><div><b>{{ document.type }}</b><small><bdi>{{ document.fileName }}</bdi> · {{ (document.fileSize ?? 0) / 1024 | number:'1.0-0' }} KB</small></div><app-status-badge [status]="document.status" /><button class="text-link" type="button" (click)="viewDocument(document)">View</button><button type="button" (click)="deleteDocument(document)">Delete</button></article> } @empty { <p class="muted">No documents uploaded yet.</p> }</div></section>
      </div>
    </section>
  `
})
export class ProfileComponent {
  private readonly fb = inject(FormBuilder); readonly auth = inject(AuthService); private readonly studentApi = inject(StudentService); private readonly userApi = inject(UserService); private readonly documentApi = inject(DocumentService);
  private readonly i18n = inject(I18nService);
  readonly completion = signal(0); readonly profileExists = signal(false); readonly documents = signal<StudentDocument[]>([]); readonly saving = signal(false); readonly changingPassword = signal(false); readonly uploading = signal(false); readonly error = signal(''); readonly success = signal(''); selectedFile: File | null = null;
  readonly documentTypes = ['CV','Passport','Transcript','GraduationCertificate','RecommendationLetter','MotivationLetter','LanguageCertificate','Other'];
  readonly accountForm = this.fb.nonNullable.group({ name: [this.auth.currentUser()?.name ?? '', [Validators.required, Validators.minLength(2)]], email: [this.auth.currentUser()?.email ?? '', [Validators.required, Validators.email]] });
  readonly passwordForm = this.fb.nonNullable.group({ currentPassword: ['', [Validators.required, Validators.maxLength(128)]], newPassword: ['', [Validators.required, Validators.minLength(6), Validators.maxLength(128)]], confirmPassword: ['', [Validators.required, Validators.maxLength(128)]] }, { validators: passwordMatchValidator('newPassword', 'confirmPassword') });
  readonly profileForm = this.fb.nonNullable.group({ phone: [''], dateOfBirth: [''], gender: [''], nationality: [''], country: [''], address: [''], university: [''], faculty: [''], department: [''], degree: [''], graduationYear: [''], GPA: [''], targetDegreeLevel: [''], preferredMajors: [''], preferredCountries: [''], englishLevel: [''], IELTS: [''], TOEFL: [''], skills: [''], languages: [''], interests: [''], bio: [''] });
  readonly uploadForm = this.fb.nonNullable.group({ type: ['', Validators.required] });
  constructor() { this.load(); }
  load(): void { forkJoin({ user: this.userApi.getMe(), docs: this.documentApi.list() }).subscribe({ next: ({ user, docs }) => { this.accountForm.patchValue({ name: user.data.name, email: user.data.email }); this.documents.set(docs.data); }, error: (error: unknown) => this.error.set(apiErrorMessage(error)) }); this.studentApi.getProfile().subscribe({ next: ({ data }) => { this.profileExists.set(true); this.completion.set(data.completionPercentage); this.patchProfile(data.profile); }, error: () => undefined }); }
  saveAccount(): void { if (this.accountForm.invalid) return; this.saving.set(true); this.error.set(''); this.success.set(''); this.userApi.updateMe(this.accountForm.getRawValue()).pipe(finalize(() => this.saving.set(false))).subscribe({ next: ({ data }) => { this.auth.refreshUser(data); this.success.set('Account details updated.'); }, error: (error: unknown) => this.error.set(apiErrorMessage(error)) }); }
  changePassword(): void { this.passwordForm.markAllAsTouched(); if (this.passwordForm.invalid || this.changingPassword()) return; this.changingPassword.set(true); this.error.set(''); this.success.set(''); this.userApi.changePassword(this.passwordForm.getRawValue()).pipe(finalize(() => this.changingPassword.set(false))).subscribe({ next: () => { this.passwordForm.reset({ currentPassword: '', newPassword: '', confirmPassword: '' }); this.success.set('Password changed successfully.'); }, error: (error: unknown) => this.error.set(apiErrorMessage(error, 'Could not change the password. Please try again.')) }); }
  saveProfile(): void { if (this.profileForm.invalid) return; this.saving.set(true); this.error.set(''); const payload = this.toPayload(); const request = this.profileExists() ? this.studentApi.updateProfile(payload) : this.studentApi.createProfile(payload); request.pipe(finalize(() => this.saving.set(false))).subscribe({ next: () => { this.profileExists.set(true); this.success.set('Opportunity Passport updated.'); this.studentApi.getProfile().subscribe(({ data }) => this.completion.set(data.completionPercentage)); }, error: (error: unknown) => this.error.set(apiErrorMessage(error)) }); }
  pickFile(event: Event): void { this.selectedFile = (event.target as HTMLInputElement).files?.[0] ?? null; }
  upload(): void { if (!this.selectedFile || this.uploadForm.invalid) return; this.uploading.set(true); this.documentApi.upload(this.uploadForm.controls.type.value, this.selectedFile).pipe(finalize(() => this.uploading.set(false))).subscribe({ next: ({ data }) => { this.documents.update((items) => [data, ...items.filter((item) => item.type !== data.type)]); this.selectedFile = null; this.uploadForm.reset(); }, error: (error: unknown) => this.error.set(apiErrorMessage(error)) }); }
  deleteDocument(document: StudentDocument): void { const message = this.i18n.language() === 'ar' ? `حذف ${document.type}؟` : `Delete ${document.type}?`; if (!confirm(message)) return; this.documentApi.delete(document._id).subscribe({ next: () => this.documents.update((items) => items.filter((item) => item._id !== document._id)), error: (error: unknown) => this.error.set(apiErrorMessage(error)) }); }
  viewDocument(document: StudentDocument): void { const preview = window.open('', '_blank'); this.documentApi.view(document._id).subscribe({ next: (blob) => { const url = URL.createObjectURL(blob); if (preview) preview.location.href = url; else window.open(url, '_blank'); setTimeout(() => URL.revokeObjectURL(url), 60_000); }, error: (error: unknown) => { preview?.close(); this.error.set(apiErrorMessage(error, 'Could not open the document.')); } }); }
  initials(): string { return (this.auth.currentUser()?.name ?? 'SA').split(' ').slice(0, 2).map((word) => word[0]).join('').toUpperCase(); }
  private patchProfile(profile: StudentProfile): void { this.profileForm.patchValue({ ...profile, dateOfBirth: profile.dateOfBirth?.slice(0,10) ?? '', gender: profile.gender ?? '', degree: profile.degree ?? '', targetDegreeLevel: profile.targetDegreeLevel ?? '', englishLevel: profile.englishLevel ?? '', graduationYear: profile.graduationYear?.toString() ?? '', GPA: profile.GPA?.toString() ?? '', IELTS: profile.IELTS?.toString() ?? '', TOEFL: profile.TOEFL?.toString() ?? '', preferredMajors: profile.preferredMajors?.join(', ') ?? '', preferredCountries: profile.preferredCountries?.join(', ') ?? '', skills: profile.skills?.join(', ') ?? '', languages: profile.languages?.join(', ') ?? '', interests: profile.interests?.join(', ') ?? '' }); }
  private toPayload(): StudentProfile { const raw = this.profileForm.getRawValue(); const strings = (value: string) => value.split(',').map((item) => item.trim()).filter(Boolean); const payload: StudentProfile = { phone: raw.phone || undefined, dateOfBirth: raw.dateOfBirth || undefined, gender: (raw.gender || undefined) as StudentProfile['gender'], nationality: raw.nationality || undefined, country: raw.country || undefined, address: raw.address || undefined, university: raw.university || undefined, faculty: raw.faculty || undefined, department: raw.department || undefined, degree: (raw.degree || undefined) as StudentProfile['degree'], graduationYear: raw.graduationYear ? Number(raw.graduationYear) : undefined, GPA: raw.GPA ? Number(raw.GPA) : undefined, targetDegreeLevel: (raw.targetDegreeLevel || undefined) as StudentProfile['targetDegreeLevel'], preferredMajors: strings(raw.preferredMajors), preferredCountries: strings(raw.preferredCountries), englishLevel: (raw.englishLevel || undefined) as StudentProfile['englishLevel'], IELTS: raw.IELTS ? Number(raw.IELTS) : undefined, TOEFL: raw.TOEFL ? Number(raw.TOEFL) : undefined, skills: strings(raw.skills), languages: strings(raw.languages), interests: strings(raw.interests), bio: raw.bio || undefined }; return payload; }
}
